### PR TITLE
How to work on these docs

### PR DESCRIPTION
**Pull request by caro401**
The target audience for these docs is anyone on the team, they should be accessible and clear to everyone (but probably currently aren't - that's what this review is for!). 

You can see the page as it will be published here: https://30-how-to-docs.kiara-website.pages.dev/internal/how-to-write-these-docs

I'd appreciate review from anyone/everyone, specifically about these points below, but also any other thoughts you have.
- **topics covered** - is everything you need to know there? Is is clear to you when there's a section you don't need to care about? 
- **structure** - does the information come at you in the right order? can you easily find what you need to know?
- **clarity of writing** - is everything clearly explained? is the tone of voice ok? Have I used jargon/weird phrasing that doesn't make sense? Are the sentences too long/full of punctuation? Did I spell something wrong?

If there's specific comments about particular words/sentences/sections, it's easiest for me if you can put them on the relevant line(s) in the markdown file if possible.

I've requested review from @CBurge95 initially (as a representative target user), as I can't add Cosimo or Petros. This might mean they don't have full write access/permissions on this repo? Review/opinions/thoughts from anyone/everyone on the team would be much appreciated if you have time!

### CODE REVIEW

**Comment by Glottocrisio** [comment]
Dear Caro, first of all thank you very much for your effort. The website looks very tidy and beautiful. I checked the document for which you asked for a request, and from my side is a full pass on all the above mentioned test-points. 

If I am obliged to give some hints, then I would say that I would put the section "Running this site on your computer" at the very end, because is also something one would do "if things go wrong". I like the fact that you write as you speak, it makes everything more real, therefore easier to fathom. However, be careful to always keep it synthetic, even if it is good to make it more colorful.  For instance this "Also use this process if you want to add a new page, when you’ve already drafted the content elsewhere and it’s mostly text." is important info, and you deliver it periferically. Maybe this could inserted in the title, with a slash.
Afterwards you use the expression "complicated text", and I could infer "complicated" means "not simple", and "simple" "with mostly text" from what you wrote before. Maybe there is a more straightforward way to express it.  
Even if this is only for internal use, and we are all mature adults, I would put a warning in "I just want to fix a typo", to explain bad consequences of using that updating-mode for less basic changes.
I am brainstorming... you assume we have git basics, which is barely true for myself, so I can imagine that someone among us can be a bit overwhelmed with using git commands. Therefore as soon as there is time, I would extend that part, just including the git commands needed for pulling, committing and so on (I can do it after the 5th of March).  If I can spot something else I will write you, and please let me know if there is some action I can take from my side, to solve this issue of tagging me here on git. Thank you for your work Caro, as a wannabe-module-writer, I feel already relieved

**Comment by CBurge95** [comment]
Hi Caro, this all looks great to me, thanks so much for doing this!!

I have a couple of questions / suggestions that may just be me (some of which I might have solutions for anyway but don't want to just make edits!!)

1. I think re the git commands / instructions we can just link out to helpful guides - we shouldn't be expected to hold all the information for these, either for internal or external users - I can find something that we can link in there that's 'researcher' (aka baby coder) accessible!!

2. Is it worth mentioning that part of the plugin docs (aka specific operation docs) are only editable in kiara itself? (If I've understood that correctly!) 

3. Just a quick question on some of success / failure results and running things to check - is that done in the CMS / GitHub or in terminal? Sorry if that's obvious or if I've not read it clearly enough!

4. Lastly I think we can add some really clear instructions about what can be automatically pushed to main and what *has* to be a request for review - I'm happy to write this up & I think it might be a conversation to be had in a dev meeting about oversight vs independence, but just wanted to make a note of it here while I thought of it!

But all in all super fab, I would feel confident doing this now!! (Even if I am probably a classic case of 'when things go wrong'!)

**Comment by makkus** [comment]
I don't have any comments apart from what others have said, just also wanted to say thanks for doing this, it looks great, and it makes my life a lot easier just being able to dump information in this repo and not have to worry about structure. That, plus not having a commonly agreed upon place always made me more hesitant to write up stuff than should have been the case, so I'm super happy we finally have that. Thanks again, this is brilliant!

**Comment by caro401** [comment]
@Glottocrisio do the above changes address your comments? Thanks @CBurge95 for finding that great git article, apologies to the team for assuming that git/github process would be familiar and comfortable for you.

**Comment by caro401** [comment]
@CBurge95 
> 4. Lastly I think we can add some really clear instructions about what can be automatically pushed to main and what has to be a request for review - I'm happy to write this up & I think it might be a conversation to be had in a dev meeting about oversight vs independence, but just wanted to make a note of it here while I thought of it!

Let's discuss this in the dev meeting? In this case, I trust the team to mostly just push to main, and would prefer the risk of a slightly imperfect article being live than adding a load of git-related overhead to you, but we should decide together whether that's appropriate. 

May be worth generally discussing how we issue/git/hub/review in the dev meeting too, but I don't really want to address that can of worms here.

**Comment by Glottocrisio** [comment]
> @Glottocrisio do the above changes address your comments? Thanks @CBurge95 for finding that great git article, apologies to the team for assuming that git/github process would be familiar and comfortable for you.

Thank you Caro, yes perfectly. Nevertheless, I am yet not entirely sure on moving the paragraph, it might be a matter of personal taste.

**Comment by caro401** [comment]
I'm going to merge this for now, so there's something published in the live site. Any more questions/ideas/requests for clarification, please make a new issue labelled `docs-platform`

**Pull request merged**
